site_name: rain

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_docstring_functions: true
            show_docstring_modules: true
            show_docstring_description: true

nav:
  - index.md
  - installation.md
  - registration.md
  - setup_server.md
  - setup_client.md
  - run_server.md
  - run_client.md
  - api.md
