site_name: rain

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/danielk333/rain

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_docstring_functions: true
            show_docstring_modules: true
            show_docstring_description: true

nav:
  - Home: index.md
  - Guides:
    - installation.md
    - registration.md
    - setup_server.md
    - plugins.md
    - run_server.md
    - setup_client.md
    - run_client.md
  - Reference:
    - messages.md
    - logging.md
    - api.md
